name: devy_boiler_plate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  connection_notifier: ^2.0.1
  connectivity_plus: ^6.0.2
  crypto: ^3.0.3
  dio: ^5.4.2+1
  dio_smart_retry: ^6.0.0
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.2
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.2
  retry: ^3.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http_parser: ^4.0.2
  logger: ^2.2.0

dependency_overrides: 
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lottie/
    - .env
